spring:
  # 激活额外的RocketMQ配置文件
  profiles:
    active: rocketmq
  
  # 应用配置
  application:
    name: rocketmq-demo

# 服务器配置
server:
  port: 8080

# 日志配置
logging:
  level:
    root: INFO
    com.example.rocketmqdemo: DEBUG